# Generated by Django 4.0.5 on 2022-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
