# Generated by Django 4.0.5 on 2022-06-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_indo',
            },
        ),
        migrations.AlterModelTable(
            name='article',
            table='blog_info',
        ),
    ]
